//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NS_Education.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class B_Partner
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public B_Partner()
        {
            this.B_PartnerItem = new HashSet<B_PartnerItem>();
            this.Resver_Throw_Food = new HashSet<Resver_Throw_Food>();
        }
    
        public int BPID { get; set; }
        public int BCID { get; set; }
        public string Code { get; set; }
        public string Title { get; set; }
        public string Compilation { get; set; }
        public int BSCID { get; set; }
        public string Email { get; set; }
        public bool CleanFlag { get; set; }
        public int CleanPrice { get; set; }
        public System.DateTime CleanSDate { get; set; }
        public System.DateTime CleanEDate { get; set; }
        public bool ActiveFlag { get; set; }
        public bool DeleteFlag { get; set; }
        public System.DateTime CreDate { get; set; }
        public int CreUID { get; set; }
        public System.DateTime UpdDate { get; set; }
        public int UpdUID { get; set; }
        public string Note { get; set; }
    
        public virtual B_Category B_Category { get; set; }
        public virtual B_StaticCode B_StaticCode { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<B_PartnerItem> B_PartnerItem { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Resver_Throw_Food> Resver_Throw_Food { get; set; }
    }
}
