//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NS_Education.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Lookup
    {
        public string Title { get; set; }
        public string Category { get; set; }
        public string GetListEndpoint { get; set; }
        public string SubmitEndpoint { get; set; }
        public string DeleteEndpoint { get; set; }
        public string GetEndpoint { get; set; }
        public string Field1Title { get; set; }
        public string Field1PropertyName { get; set; }
        public string Field2Title { get; set; }
        public string Field2PropertyName { get; set; }
        public string Field3Title { get; set; }
        public string Field3PropertyName { get; set; }
        public string Field4Title { get; set; }
        public string Field4PropertyName { get; set; }
        public string Field5Title { get; set; }
        public string Field5PropertyName { get; set; }
        public string IdPropertyName { get; set; }
    }
}
