//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NS_Education.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Resver_Site
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Resver_Site()
        {
            this.Resver_Device = new HashSet<Resver_Device>();
            this.Resver_Throw = new HashSet<Resver_Throw>();
        }
    
        public int RSID { get; set; }
        public int RHID { get; set; }
        public System.DateTime TargetDate { get; set; }
        public int BSID { get; set; }
        public int BSCID { get; set; }
        public int BOCID { get; set; }
        public string PrintTitle { get; set; }
        public string PrintNote { get; set; }
        public int UnitPrice { get; set; }
        public int FixedPrice { get; set; }
        public int QuotedPrice { get; set; }
        public int SortNo { get; set; }
        public string Note { get; set; }
        public bool DeleteFlag { get; set; }
        public System.DateTime CreDate { get; set; }
        public int CreUID { get; set; }
        public System.DateTime UpdDate { get; set; }
        public int UpdUID { get; set; }
        public Nullable<System.TimeSpan> ArriveTimeStart { get; set; }
        public Nullable<System.TimeSpan> ArriveTimeEnd { get; set; }
        public string ArriveDescription { get; set; }
        public string TableDescription { get; set; }
        public byte[] SeatImage { get; set; }
    
        public virtual B_OrderCode B_OrderCode { get; set; }
        public virtual B_SiteData B_SiteData { get; set; }
        public virtual B_StaticCode B_StaticCode { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Resver_Device> Resver_Device { get; set; }
        public virtual Resver_Head Resver_Head { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Resver_Throw> Resver_Throw { get; set; }
    }
}
